"""Добавлено поле event_id в LunchSlot

Revision ID: 3a3564068fe1
Revises: b9c18b4370a9
Create Date: 2025-06-15 18:14:13.600002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3564068fe1'
down_revision: Union[str, None] = 'b9c18b4370a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_slots', schema=None) as batch_op:
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
