"""Добавлено поле manager_id в LunchSlot

Revision ID: 6db30a12fb2f
Revises: c2c85e51e374
Create Date: 2025-06-04 17:33:54.755993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db30a12fb2f'
down_revision: Union[str, None] = 'c2c85e51e374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunch_slots', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lunch_slots', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lunch_slots', type_='foreignkey')
    op.drop_column('lunch_slots', 'manager_id')
    # ### end Alembic commands ###
