"""Добавлено поле is_booked в LunchSlot

Revision ID: aa8c892fb183
Revises: f39048a86252
Create Date: 2025-06-05 11:55:18.440558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8c892fb183'
down_revision: Union[str, None] = 'f39048a86252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunch_slots', sa.Column('is_booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lunch_slots', 'is_booked')
    # ### end Alembic commands ###
